# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-23 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('quoteContent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likedBy', models.ManyToManyField(related_name='likes', to='Exam.User')),
                ('postedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotesPosted', to='Exam.User')),
            ],
        ),
    ]
